#ifndef CANDY_TYPE_H_
#define CANDY_TYPE_H_

enum class CandyType {
    NORMAL_CANDY,
    HORIZONTAL_STRIPED_CANDY,
    VERTICAL_STRIPED_CANDY,
    BOMB_CANDY,
    WILD_CANDY,
    NUM_CANDIES
};
#endif /* CANDY_TYPE_H */