#ifndef GAMESTATE_H_
#define GAMESTATE_H_

enum class GameState {
    DEFAULT,
    SWAP_CANDIES,
    DELETE_CANDIES,
    SWAPPING_ANIMATION,
    UPDATE_BOARD_AFTER_DELETION,
    MOVING_ANIMATION,
    CHECK_FOR_MATCHES
};
#endif /* GAMESTATE_H_ */