name: 'Install packages'
description: 'Install required packages'

runs:
  using: "composite"
  steps:
    # Common Linux dependencies
    - name: Install Linux Dependencies
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libmysqlclient-dev libssl-dev
        # https://github.com/llvm/llvm-project/issues/78354
        sudo sysctl vm.mmap_rnd_bits=28
       # Verify SDL2, MySQL, and OpenSSL installation
    - name: Verify SDL2 installation
      shell: bash
      run: |
        if pkg-config --exists sdl2; then
          echo "SDL2 is installed"
        else
          echo "SDL2 is NOT installed"
          exit 1
        fi

    - name: Verify MySQL installation
      shell: bash
      run: |
        if dpkg-query -l | grep -q libmysqlclient-dev; then
          echo "MySQL client is installed"
        else
          echo "MySQL client is NOT installed"
          exit 1
        fi

    - name: Verify OpenSSL installation
      shell: bash
      run: |
        if dpkg-query -l | grep -q libssl-dev; then
          echo "OpenSSL is installed"
        else
          echo "OpenSSL is NOT installed"
          exit 1
        fi

    - name: Set up SDL2 path
      shell: bash
      run: |
        export SDL2_DIR=/usr/include/SDL2
        export SDL2_image_DIR=/usr/include/SDL2
        export SDL2_ttf_DIR=/usr/include/SDL2
        
    # Also see https://github.com/actions/runner-images/discussions/9446#discussioncomment-8668538
    - name: Install Clang ${{ matrix.clang_ver }}
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_msan == true
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x ./llvm.sh
        sudo ./llvm.sh ${{ matrix.clang_ver }}

    - name: Install libc++ (Linux Clang ${{ matrix.clang_ver }})
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_msan == true
      run: |
        # sudo apt-get update
        sudo apt-get install --no-install-recommends libc++-${{ matrix.clang_ver }}-dev libc++abi-${{ matrix.clang_ver }}-dev

    - name: Install valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        # sudo apt-get update
        sudo apt-get install --no-install-recommends valgrind
